### ISSUE TITLE
18F's great post has been removed

### ISSUE THREAD

**Issue by zoidbergwill** [williln/heyguys.cc#11]
I saw this via https://twitter.com/peterkarman/status/1038174750542053376, linking to the PR unpublishing it: https://github.com/18F/18f.gsa.gov/pull/2881

Should we change the link to one from archive.org?
https://web.archive.org/web/20170903230255/https://18f.gsa.gov/2016/01/12/hacking-inclusion-by-customizing-a-slack-bot/

**Comment by jefftriplett** [comment]
@zoidbergwill great point and sorry it took so long to see it. the archive.org post is probably the best option.

**Comment by annepetersen** [comment]
Republished. https://github.com/18F/18f.gsa.gov/commits/7a6cf04f63d83f9b41820e36e15a7a3064311d82/_posts/2016-01-12-hacking-inclusion-by-customizing-a-slack-bot.md
