### ISSUE TITLE
Non-welcoming language on heyguys.cc

### ISSUE THREAD

**Issue by nkuttler** [williln/heyguys.cc#17]
Unfortunately I have made the experience that the text on heyguys.cc uses non-welcoming language. Starting off with '"Hey guys" is a common salutation, but it's not gender neutral.' is non-welcoming because it is factually incomplete. The statement can lead to controversy when the site is linked to because people for whom "hey guys" is a non-gendered salutation can feel excluded and not welcome, and they may not be very receptive for the rest of the text.

I think it would be better to promote non-gendered language with a more welcoming text, something like

> "Hey guys" is a common salutation, but it's not gender neutral for everybody. While it is non-gendered to some, people who aren't men can feel excluded when addressed as "guys".

I would also remove the part "even if that is not the intent". Miscommunication needs two parties, and it is caused by the speaker and the listener having a different understanding of "guys". The current intent statement blames only the speaker for the miscommunication, I tried to make my example above blameless instead, but I'm sure it's not perfect either.

I think with a few minor changes the text could be more welcoming and more people would react positively to it.

**Comment by nkuttler** [comment]
I think it would also be good to remove the source "Hacking inclusion: How we customized a bot to gently correct people who use the word ‘guys’, Maya Benari, 18F.". Like mentioned above, putting the blame for miscommunication on one side only is not welcoming.

**Comment by williln** [comment]
Thanks for the comment.  

If "guys" isn't gender neutral for everyone, then it isn't gender neutral. In most cases, there isn't a way to know if everyone in your audience considers "guys" to be a gender neutral term; the point of this site is to teach people other terms to use that are more inclusive. My experience with the Slackbot is that people react very positively to it -- it's a gentle nudge to use a different term, not a harsh callout. 

I appreciate your thoughts, but I disagree with these suggestions.
