### ISSUE TITLE
Comrades alternative duality

### ISSUE THREAD

**Issue by erikvanek** [williln/heyguys.cc#18]
Hey eveyrone.

I like this project a lot. I'd suggest to remove one alternative from it, which some people mind find quite offensive and that it _comrade_.

Imagine you're from a country that was occupied by Russia for 40+ years and people were forced to use the word _comrade_ when talking to each other. It does not have a good connotation in Central Europe.

Cheers.

**Comment by cosu** [comment]
As a Romanian, I fully agree with this. I visited this project to complain about this very thing.

If you want to be neutral you should also think of other implications than just gender.

**Comment by jefftriplett** [comment]
Thank you for bringing this up and for the contribution in #21. Merged!

**Comment by lokhman** [comment]
@erikvanek FYI, Russia is not the same as Soviet Union and the communist regime that was leading it for several decades. I am from Russia and I find your wording offensive to Russia and Russian people. You cannot change the history but you need to be accurate in how you explain yourself in the modern world. Suggesting to remove the word "comrade" for "political associations" would be enough, there was no need to speculate about "occupation by Russia for 40+ years", etc. This is just the wrong direction.
